#!/usr/bin/env perl
use strict;
use warnings;
use File::Spec;

my $build_lib;

BEGIN {
    $build_lib = File::Spec->catdir( $ENV{MANULC_SRC} || '.', 'build_lib' );
}

use lib $build_lib;

use Dist::Zilla::App;
# Let build --version know what to report:
our $VERSION = 'v0.001.001';

# PODNAME:  dzil
# ABSTRACT: do stuff with your dist
Dist::Zilla::App->run;

exit;
