#!/usr/bin/env perl
use v5.24;
use open qw<:std :encoding(UTF-8)>;
use Path::Tiny;

my $build_lib;

BEGIN {
    $build_lib = path( ( $ENV{MANULC_SRC} || '.' ) . '/build_lib' )->absolute->stringify;
}

use lib $build_lib;

use Dist::Zilla::App;
# Let build --version know what to report:
our $VERSION = 'v0.001.001';

# PODNAME:  dzil
# ABSTRACT: do stuff with your dist
Dist::Zilla::App->run;

exit;
